"""Add Platform.image

Revision ID: 0ae0fb9257cc
Revises: c1ecdaa85d24
Create Date: 2025-08-13 15:41:07.001284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae0fb9257cc'
down_revision = 'c1ecdaa85d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.drop_column('image')

    op.drop_table('onboarding_progress')
    # ### end Alembic commands ###
