"""empty message

Revision ID: 1fe28384b955
Revises: 9d3545f26d82
Create Date: 2025-07-26 15:01:04.178876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe28384b955'
down_revision = '9d3545f26d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('developer')
        batch_op.drop_column('release_year')
        batch_op.drop_column('genre')
        batch_op.drop_column('image_url')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('developer', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
