"""add user genre preference

Revision ID: 53247548b7cc
Revises: 0387f85e42ce
Create Date: 2025-07-30 17:13:45.323249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53247548b7cc'
down_revision = '0387f85e42ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_genre_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_genre_preference')
    # ### end Alembic commands ###
