"""empty message

Revision ID: 5544be9b7ed6
Revises: eb0ced10e1e6
Create Date: 2025-08-07 17:41:21.911052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5544be9b7ed6'
down_revision = 'eb0ced10e1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
