"""empty message

Revision ID: 790bbba76051
Revises: ef58d06ac535
Create Date: 2025-08-04 18:03:10.177191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790bbba76051'
down_revision = 'ef58d06ac535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('released', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rawg_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('rawg_id')
        batch_op.drop_column('rating')
        batch_op.drop_column('released')
        batch_op.drop_column('background_image')

    # ### end Alembic commands ###
