"""empty message

Revision ID: c1ecdaa85d24
Revises: ec466ff062f8
Create Date: 2025-08-11 17:49:53.423032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ecdaa85d24'
down_revision = 'ec466ff062f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding them to avoid duplicate column errors
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('user')]

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Only add columns if they don't exist
        if 'role' not in columns:
            batch_op.add_column(
                sa.Column('role', sa.String(length=50), nullable=True))
        if 'is_active' not in columns:
            batch_op.add_column(
                sa.Column('is_active', sa.Boolean(), nullable=True))
        if 'profile_image_url' not in columns:
            batch_op.add_column(
                sa.Column('profile_image_url', sa.String(length=500), nullable=True))

        # Check if constraint exists before creating it
        try:
            batch_op.create_unique_constraint('uq_user_nickname', ['nickname'])
        except Exception:
            # Constraint might already exist, skip
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('is_active')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
